
dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
  - "2.7"
  - "3.3"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
script:
  - cd decide
  - coverage run --branch --source=. ./manage.py test --keepdb --with-xunit
  - coverage xml
  - python-codacy-coverage -r coverage.xml
env:
  - DJANGO_VERSION=2.1.13
  - DJANGO_VERSION=2.2.6